Repository openshift/ovirt-csi-driver, pull requests merged in 2021-08, with the labels that each got.

#83 Bug 1983933: CSI expansion should work in offline mode
  pkg/service/controller.go
  pkg/service/helper.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#84 Bug 1989101: Replaced Roy with myself as owner/reviewer
  OWNERS
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#82 Bug 1973076: Bug 1985795: Fix create volume, configure disk format based on storage domain and wait for disk to be ok
  pkg/service/controller.go
  pkg/service/helper.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
